# Use postgres/example user/password credentials
version: '3.1'

services:
  prod-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    container_name: prod-db
    volumes:
      - ../data:/var/lib/postgresql/data
      - ../dump.sql:/dump.sql #Temp

  prod-backend:
    image: codespells-backend
    build: ./backend
    restart: always
    ports:
      - 8080:8000
    depends_on: 
      - prod-db
    volumes:
      - ./backend:/usr/src/app
      - ./backend/.prod-env:/usr/src/app/.env
      - /usr/src/app/node_modules
    command: "scripts/setup-and-run.sh"
    container_name: prod-backend
    env_file:
      - ./backend/.prod-env

  prod-frontend:
    image: codespells-frontend
    build: ./frontend
    restart: always
    ports:
      - 80:3000
    depends_on: 
      - prod-backend
    volumes:
      - ./frontend:/usr/src/app
      - ./frontend/.prod-env:/usr/src/app/.env
      - /usr/src/app/node_modules
    container_name: prod-frontend
    env_file:
      - ./frontend/.prod-env

  prod-lang-server:
    image: codespells-lang-server
    build: ./lang-server
    restart: always
    ports:
      - 8090:8090
    volumes:
      - ./lang-server:/usr/src/app
    container_name: prod-lang-server