
# Use postgres/example user/password credentials
version: '3.1'

networks: 
  dev-codespells-network: 

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks: 
      - dev-codespells-network

  backend:
    image: codespells-backend
    build: ./backend
    restart: always
    ports:
      - 8000:8000
    depends_on: 
      - "db"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: "./scripts/setup-and-run.sh"
    container_name: backend
    env_file:
      - ./backend/.env
    networks: 
      - dev-codespells-network

  frontend:
    image: codespells-frontend
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    depends_on: 
      - "backend"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: frontend
    env_file:
      - ./frontend/.env
    networks: 
      - dev-codespells-network

  lang-server:
    image: codespells-lang-server
    build: ./lang-server
    restart: always
    ports:
      - 8091:8090
    volumes:
      - ./lang-server:/usr/src/app
    container_name: lang-server
    networks: 
      - dev-codespells-network

  racket-bridge:
    image: racket-bridge
    build: ./nexus-client
    restart: always
    ports:
      - 8082:8082
      - 8888:8888
    volumes:
      - ./nexus-client:/usr/src/app
    container_name: racket-bridge
  