CREATE TABLE IF NOT EXISTS game_states (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  letters_guessed TEXT NOT NULL,
  secret_target TEXT NOT NULL,
  target_word TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);