CREATE TABLE IF NOT EXISTS follows (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  follower_id INTEGER NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP DEFAULT now() NOT NULL,
  CONSTRAINT fk_user
    FOREIGN KEY(user_id)
      REFERENCES users(id),
  CONSTRAINT fk_follower
    FOREIGN KEY(follower_id)
      REFERENCES users(id)
);
